# Stages em ordem
stages:
  - test
  - pages

# Imagem default (não usada no job de Playwright)
image: node:18-alpine

# Cache NPM (seguro entre imagens diferentes via prefix)
cache:
  key:
    files:
      - package-lock.json
    prefix: "npm-${CI_JOB_IMAGE}"
  paths:
    - .npm/_cacache/
  policy: pull-push

variables:
  NODE_ENV: production
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
  CI: "true"

default:
  interruptible: true
  before_script:
    - node -v
    - npm -v
    # Se usar registry privado do npm:
    # - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

# ===============================
# Testes BDD (Cucumber + Playwright)
# ===============================
test_cucumber:
  stage: test
  image: mcr.microsoft.com/playwright:v1.48.2-jammy
  script:
    - npm ci
    # Rode seus testes BDD. Ajuste o comando abaixo ao que você usa:
    # Exemplo com cucumber-js, gravando JSON:
    - npx cucumber-js --format json:reports/cucumber.json --publish-quiet
    # Converte cucumber.json -> JUnit para o Test Report do GitLab
    - npx --yes cucumber-junit < reports/cucumber.json > reports/junit.xml
    # Gera evidência HTML para publicação no Pages
    - npx --yes multiple-cucumber-html-reporter --jsonDir reports --reportPath public/cucumber-report --pageTitle "E2E - Cucumber"
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - reports/               # mantém o cucumber.json e o junit.xml
      - public/cucumber-report # site estático da evidência
    reports:
      junit: reports/junit.xml
  rules:
    # Executa em Merge Requests
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Executa em branches (exceto tags)
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_TAG == null'

# ===============================
# Publicação da evidência (GitLab Pages)
# ===============================
pages:
  stage: pages
  needs: ["test_cucumber"]   # garante pegar artifacts do job de teste
  script:
    # Nada a construir aqui; apenas garantir que a pasta public existe
    - test -d public || mkdir -p public
    - echo "Publicando evidências do Cucumber em GitLab Pages"
  artifacts:
    paths:
      - public
  rules:
    # Publica somente no branch padrão (ex.: main)
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'